In [56]:
# Parse presidential election results

import pandas as pd

In [57]:
PRES_CSV = '../raw_data/president_pop_vote_results/1976-2016-president.csv'

In [58]:
df = pd.read_csv(PRES_CSV, delimiter=',', encoding='utf-8')
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
0,1976,Alabama,AL,1,63,41,US President,"Carter, Jimmy",democrat,False,659170,1182850,20171015,NaN
1,1976,Alabama,AL,1,63,41,US President,"Ford, Gerald",republican,False,504070,1182850,20171015,NaN
2,1976,Alabama,AL,1,63,41,US President,"Maddox, Lester",american independent party,False,9198,1182850,20171015,NaN
3,1976,Alabama,AL,1,63,41,US President,"Bubar, Benjamin """"Ben""""",prohibition,False,6669,1182850,20171015,NaN
4,1976,Alabama,AL,1,63,41,US President,"Hall, Gus",communist party use,False,1954,1182850,20171015,NaN

In [59]:
# Clean
df = df[df.party.isin(['democrat', 'republican'])]
df['pop_percent'] = df['candidatevotes'] / df['totalvotes']
df = df[['state', 'state_po', 'year', 'party', 'pop_percent']]
df.head(150)

             state state_po  year       party  pop_percent
0          Alabama       AL  1976    democrat     0.557273
1          Alabama       AL  1976  republican     0.426149
7           Alaska       AK  1976  republican     0.579046
8           Alaska       AK  1976    democrat     0.356531
11         Arizona       AZ  1976  republican     0.563661
..             ...      ...   ...         ...          ...
480  Massachusetts       MA  1980    democrat     0.417498
486       Michigan       MI  1980  republican     0.489862
487       Michigan       MI  1980    democrat     0.424974
493      Minnesota       MN  1980    democrat     0.465016
494      Minnesota       MN  1980  republican     0.425587

[150 rows x 5 columns]

In [60]:
# Format
df = df.pivot_table(index=['year', 'state', 'state_po'], columns=['party'], values='pop_percent').reset_index()
df.head()

party  year       state state_po  democrat  republican
0      1976     Alabama       AL  0.557273    0.426149
1      1976      Alaska       AK  0.356531    0.579046
2      1976     Arizona       AZ  0.398000    0.563661
3      1976    Arkansas       AR  0.649617    0.349043
4      1976  California       CA  0.479548    0.497483